#############################################################################
# Makefile for building: LASReader
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Wed Sep 10 22:59:52 2014
# Project:  LASReader.pro
# Template: app
# Command: $(QMAKE) -o Makefile LASReader.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fno-strict-aliasing -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
CXXFLAGS = -pipe -std=gnu++0x -std=c++0x -O2 -g -Wall -m64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  =  -I.
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = Types.h \
		Las1_3_handler.h \
		Pulse.h \
		PulseManager.h \
      vec3d.h
SOURCES = main.cpp \
		Las1_3_handler.cpp \
		Pulse.cpp \
		PulseManager.cpp \
      vec3d.cpp
OBJECTS = main.o \
		Las1_3_handler.o \
		Pulse.o \
		PulseManager.o \
      vec3d.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = LASReader.pro
QMAKE_TARGET = LASReader
DESTDIR  = 
TARGET   = LASReader

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: LASReader.pro  /usr/lib64/qt-3.3/mkspecs/default/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile LASReader.pro
qmake: 
	@$(QMAKE) -o Makefile LASReader.pro

dist: 
	@mkdir -p .tmp/LASReader && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/LASReader/ && ( cd `dirname .tmp/LASReader` && $(TAR) LASReader.tar LASReader && $(GZIP) LASReader.tar ) && $(MOVE) `dirname .tmp/LASReader`/LASReader.tar.gz . && $(DEL_FILE) -r .tmp/LASReader

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp vec3d.cpp Las1_3_handler.h \
		Types.h \
		PulseManager.h \
		Pulse.h \
      vec3d.h

Las1_3_handler.o: Las1_3_handler.cpp vec3d.cpp Las1_3_handler.h \
		Types.h \
		PulseManager.h \
		Pulse.h \
      vec3d.h

Pulse.o: Pulse.cpp vec3d.cpp Pulse.h \
		Types.h \
      vec3d.h

PulseManager.o: PulseManager.cpp vec3d.cpp PulseManager.h \
		Pulse.h \
		Types.h \
      vec3d.h

####### Install

install:  

uninstall:  

