YOURPROJECTNAMEGOESHERE: Las1_3_handler Class Reference
Las1_3_handler Class Reference
#include <Las1_3_handler.h>
Public Member Functions
Las1_3_handler (const std::string i_filename)
default constructor
PulseManager * readFileAndGetPulseManager ()
method that reads the data and returns a pulse manager with all the waveform information of the pulses NOTE: i_pulseManager is dynamic allocated, so by calling this function, you are responsible for releasing memory afterwards.
void printPublicHeader () const
method that prints headdata
~Las1_3_handler ()
default destructor
Protected Attributes
std::string m_filename
the name of the LAS file
Types::Public_Header_Block public_header
the publi header block of the LAS1.3 file
int * i_hist
the intensity histogram of the lasfile
Types::Leica_mission_info mis_info
Leica mission information.
Types::WF_packet_Descriptor wv_info
waveform packet descriptor
Private Member Functions
void read_public_header ()
method that reads public header block
void read_variable_length_records ()
method that reads variable length records including waveform packet descriptors (up to 255)
Private Attributes
std::ifstream lasfile
saved here to avoid opening and closing the file multiple times
Static Private Attributes
static const unsigned int public_header_length = 235
Public Header length in bytes.
static const unsigned int VbleRec_header_length = 54
Variable Length Record Header length in bytes.
static const unsigned int EVLR_length = 60
Extended Variable Lenght Record Header, in Version 1.3 the only EVLR is waveform data packets.
static const unsigned int point_data_length = 57
the length of the point data
Detailed Description
Definition at line 11 of file Las1_3_handler.h.
Constructor & Destructor Documentation
Las1_3_handler::Las1_3_handler (const std::string i_filename)
default constructor
Parameters
[in] i_filename the file of the name to be read
Definition at line 13 of file Las1_3_handler.cpp.
          : m_filename(i_filename),i_hist(0)
 {
 }
Las1_3_handler::~Las1_3_handler ()
default destructor
Definition at line 274 of file Las1_3_handler.cpp.
References i_hist.
 {
     if (i_hist!=0)
     {
         delete []i_hist;
     }
 }
Member Function Documentation
void Las1_3_handler::printPublicHeader () const
method that prints headdata
Definition at line 230 of file Las1_3_handler.cpp.
References Types::Public_Header_Block::file_creation_day_of_year, Types::Public_Header_Block::file_creation_year, Types::Public_Header_Block::file_signiture, Types::Public_Header_Block::file_source_ID, Types::Public_Header_Block::generating_software, Types::Public_Header_Block::global_encoding, Types::Public_Header_Block::header_size, m_filename, Types::Public_Header_Block::max_x, Types::Public_Header_Block::max_y, Types::Public_Header_Block::max_z, Types::Public_Header_Block::min_x, Types::Public_Header_Block::min_y, Types::Public_Header_Block::min_z, Types::Public_Header_Block::number_of_point_records, Types::Public_Header_Block::number_of_points_by_return, Types::Public_Header_Block::number_of_variable_lenght_records, Types::Public_Header_Block::offset_to_point, Types::Public_Header_Block::point_data_format_ID, Types::Public_Header_Block::point_data_record_length, Types::Public_Header_Block::project_ID_GUID_data_1, Types::Public_Header_Block::project_ID_GUID_data_2, Types::Public_Header_Block::project_ID_GUID_data_3, Types::Public_Header_Block::project_ID_GUID_data_4, public_header, Types::Public_Header_Block::start_of_wf_data_Packet_record, Types::Public_Header_Block::system_identifier, Types::Public_Header_Block::version_major, Types::Public_Header_Block::version_minor, Types::Public_Header_Block::x_offset, Types::Public_Header_Block::x_scale_factor, Types::Public_Header_Block::y_offset, Types::Public_Header_Block::y_scale_factor, Types::Public_Header_Block::z_offset, and Types::Public_Header_Block::z_scale_factor.
 {
    std::cout << std::setprecision(2) << std::fixed;
    std::cout << "\nHeader file of " << m_filename << std::endl;
    std::cout << "File Signature " << public_header.file_signiture << std::endl;
    std::cout << "File Source ID  "<< public_header.file_source_ID << std::endl;
    std::cout << "Global Encoding "<< public_header.global_encoding << std::endl;
    std::cout << "Project ID - GUID data 1 " << public_header.project_ID_GUID_data_1 << std::endl;
    std::cout << "Project ID - GUID data 2 " << public_header.project_ID_GUID_data_2 << std::endl;
    std::cout << "Project ID - GUID data 3 " << public_header.project_ID_GUID_data_3 << std::endl;
    std::cout << "Project ID - GUID data 4 " << public_header.project_ID_GUID_data_4 << std::endl;
    std::cout << "Version Major " << (int) public_header.version_major << std::endl;
    std::cout << "Version Minor " << (int) public_header.version_minor << std::endl;
    std::cout << "System Identifier " << public_header.system_identifier << std::endl;
    std::cout << "Generating Software " << public_header.generating_software << std::endl;
    std::cout << "File Creation Day of Year  " << public_header.file_creation_day_of_year << std::endl;
    std::cout << "File Creation Year " << public_header.file_creation_year << std::endl;
    std::cout << "Header Size    "  <<  public_header.header_size << std::endl;
    std::cout << "Offset to point data "  <<  public_header.offset_to_point << std::endl;
    std::cout << "Number of Variable Length Records "  <<  public_header.number_of_variable_lenght_records << std::endl;
    std::cout << "Point Data Format ID (0-99 for spec) "  << (int)  public_header.point_data_format_ID << std::endl;
    std::cout << "Point Data Record Length "  <<  public_header.point_data_record_length << std::endl;
    std::cout << "Number of point records " <<  public_header.number_of_point_records << std::endl;
    std::cout << "Number of points by return  " <<  public_header.number_of_points_by_return[0] << " "
              <<  public_header.number_of_points_by_return[1]<< " "
              <<  public_header.number_of_points_by_return[2]<< " "
              <<  public_header.number_of_points_by_return[3]<< " "
              <<  public_header.number_of_points_by_return[4]  <<  std::endl;
    std::cout << "X scale factor "  <<  public_header.x_scale_factor << std::endl;
    std::cout << "Y scale factor  "  <<  public_header.y_scale_factor << std::endl;
    std::cout << "Z scale factor "  <<  public_header.z_scale_factor << std::endl;
    std::cout << "X offset  "  <<  (double) public_header.x_offset << std::endl;
    std::cout << "Y offset  " <<  (double) public_header.y_offset << std::endl;
    std::cout << "Z offset "  <<  (double) public_header.z_offset << std::endl;
    std::cout << "Max X  "  << (double) public_header.max_x << std::endl;
    std::cout << "Min X  "  << (double)  public_header.min_x << std::endl;
    std::cout << "Max Y  " <<  (double) public_header.max_y << std::endl;
    std::cout << "Min Y " <<  (double) public_header.min_y << std::endl;
    std::cout << "Max Z  " <<  (double) public_header.max_z << std::endl;
    std::cout << "Min Z  " <<  (double) public_header.min_z << std::endl;
    std::cout << "Start of Waveform Data Packet Record " <<  public_header.start_of_wf_data_Packet_record << std::endl;
 }
void Las1_3_handler::read_public_header () private
method that reads public header block
Definition at line 109 of file Las1_3_handler.cpp.
References Types::Public_Header_Block::global_encoding, lasfile, public_header, Types::Public_Header_Block::version_major, and Types::Public_Header_Block::version_minor.
 {
    lasfile.read((char *) &public_header,sizeof(public_header));
    // tests if waveform data packets are saved into that file
    // if not program terminates because it cannot handle that case
    if((public_header.global_encoding & 2 ) !=2 )
    {
       std::cerr << "Waveform Data Packets are not saved in this file.\n"
                 << "Program will terminate\n";
       exit(EXIT_FAILURE);
    }
    // test version of the file. version should be 1.3
    if (public_header.version_major!=1 || public_header.version_minor!=3)
    {
       std::cerr << "Incorrect version. Only 1.3 is allowed.\n"
                 << "Program will terminate\n";
       exit(EXIT_FAILURE);
   }
 }
void Las1_3_handler::read_variable_length_records () private
method that reads variable length records including waveform packet descriptors (up to 255)
for(unsigned int i=0; i<headdata_rec.record_length_after_header/4; ++i) { std::cout << i_hist[i] << " "; } std::cout << std::endl;
std::cout << "miss_info = " << mis_info.laster_pulse_rate << " " << mis_info.field_of_view << " " << mis_info.scanner_offset << " " << mis_info.scan_rate << " " << mis_info.fly_altitude << "\n";
Definition at line 134 of file Las1_3_handler.cpp.
References i_hist, lasfile, mis_info, Types::Public_Header_Block::number_of_variable_lenght_records, public_header, Types::Variable_Length_Record_Header::record_ID, Types::Variable_Length_Record_Header::record_length_after_header, VbleRec_header_length, and wv_info.
 {
    Types::Variable_Length_Record_Header headdata_rec;
    for(unsigned int i=0; i<public_header.number_of_variable_lenght_records;
       ++i)
    {
       lasfile.read((char *) &headdata_rec, VbleRec_header_length);
       char skip_record [headdata_rec.record_length_after_header];
       lasfile.read((char *) skip_record,headdata_rec.record_length_after_header);
       // 1001 for the intensity histogram
       /*
       #If RecordID= 1001 it is the intensity histogram
       # of 1st returns w/ intensity of 0
       # of 1st returns w/ intensity of 1
       # of 1st returns w/ intensity of 2
       #
       # of 1st returns w/ intensity of 255
       # of 2nd returns w/ intensity of 0
       # of 2nd returns w/ intensity of 1
       # of 2nd returns w/ intensity of 2
       #
       # of 2nd returns w/ intensity of 255
       # of 3rd returns w/ intensity of 0
       # of 3rd returns w/ intensity of 1
       # of 3rd returns w/ intensity of 2
       #
       # of 3rd returns w/ intensity of 255
       # of returns with AGC value of 0
       # of returns with AGC value of 1
       # of returns with AGC value of 2
       #
       # of returns with AGC value of 255
       # of all returns with intensity of 0
       # of all returns with intensity of 1
       # of all returns with intensity of 2
       #
       # of all returns with intensity of 255
       */
       if(headdata_rec.record_ID == 1001)
       {
          i_hist = new (std::nothrow) int[headdata_rec.record_length_after_header/4];
          if(i_hist==0)
          {
              std::cout << "Memory assignment failed in Las1_3_handler\n"
                        << "Program will terminate\n";
              exit(EXIT_FAILURE);
          }
          memcpy((void *)i_hist,(void *)skip_record,headdata_rec.record_length_after_header);
       }
       // 1002 for Leica mission info containing
       /*
       #If RecordID= 1002 it is Leica mission info containing
       #0_ Laser Pulserate: 1 Hz
       #1_ Field Of View: 0.1 degrees
       #2_ Scanner Offset: 1 ticks
       #3_ Scan Rate:  0.1 Hz
       #4_ Flying Altitude (AGL): meters
       #5_ GPS Week Number at start of line:   week
       #6_ GPS Seconds of Week at start of line: seconds
       #7_ Reserved
       #NOTE Leica definition says this record contains 26 bytes but it actually contains only 22 so not sure what is what...
       # By comparisson with FlightLineLog fields 0,3,4,5 and 6 are ok
       */
       else if (headdata_rec.record_ID == 1002)
       {
          memcpy((void *) &mis_info,(void *)skip_record,sizeof(mis_info));
       }
       else if (headdata_rec.record_ID == 1003)
       {
       }
       else if (headdata_rec.record_ID>=100 && headdata_rec.record_ID<356)
       {
          memcpy((void *) &wv_info, (void *) skip_record, sizeof(wv_info));
 //         std::cout <<  "//--------------------------------------------------\n"
 //                   <<"bits per sample = " << (int) wv_info.bits_per_sample << "\n"
 //                   << "waveform compression type = " << (int)  wv_info.wf_compression_type << "\n"
 //                   << "number of samples = " << (int)  wv_info.number_of_samples << "\n"
 //                   << "temporal sample spacing = " << (int)  wv_info.temporal_sample_spacing << "\n"
 //                   << "Digitizer Gain = " <<(int)  wv_info.digitizer_gain<< "\n"
 //                   << "Digitizer Offset = " << (int) wv_info.digitizer_offset << "\n";
       }
    }
 }
PulseManager * Las1_3_handler::readFileAndGetPulseManager ()
method that reads the data and returns a pulse manager with all the waveform information of the pulses NOTE: i_pulseManager is dynamic allocated, so by calling this function, you are responsible for releasing memory afterwards.
Definition at line 22 of file Las1_3_handler.cpp.
References PulseManager::addPoint(), Types::Data_Point_Record_Format_4::byte_offset_to_wf_packet_data, Types::Data_Point_Record_Format_4::classification, discreteWithoutWaveform, lasfile, m_filename, Types::Public_Header_Block::number_of_point_records, Types::Public_Header_Block::offset_to_point, Types::Public_Header_Block::point_data_record_length, public_header, read_public_header(), read_variable_length_records(), Types::Data_Point_Record_Format_4::returnNo_noOfRe_scanDirFla_EdgeFLn, PulseManager::sortDiscretePoints(), Types::Public_Header_Block::start_of_wf_data_Packet_record, Types::Data_Point_Record_Format_4::wave_packet_descriptor_index, Types::Data_Point_Record_Format_4::wf_packet_size_in_bytes, and wv_info.
 {
    lasfile.open(m_filename.c_str(),std::ios::binary);
    if(!lasfile.is_open())
    {
       std::cerr << "File not found \n";
    }
    read_public_header();
    read_variable_length_records();
    //method that reads point data records
    //---------------------------------------------------------------
    PulseManager *i_pulseManager =
            new (std::nothrow) PulseManager(public_header,wv_info);
    if(i_pulseManager==0)
    {
        std::cerr << "Error: Memory could not be allocated\n";
        exit(EXIT_FAILURE);
    }
    Types::Data_Point_Record_Format_4 point_info;
    lasfile.seekg((int) public_header.offset_to_point);
    unsigned int count=0;
    unsigned int countDiscrete = 0;
    for(unsigned int i=0; i< public_header.number_of_point_records; ++i)
    {
       lasfile.read((char *) &point_info, (int) public_header.point_data_record_length);
       int wave_offset = public_header.start_of_wf_data_Packet_record +
               point_info.byte_offset_to_wf_packet_data;
       if((int)point_info.classification!=7)
       {
          if( point_info.wave_packet_descriptor_index!=0 &&
                  (unsigned int)(point_info.returnNo_noOfRe_scanDirFla_EdgeFLn&7)==1 )
            {
               count++;
               char *wave_data = new (std::nothrow) char [point_info.wf_packet_size_in_bytes];
               if(wave_data==0)
               {
                   std::cerr << "Fail assigning memory in file Las1_3_handler.cpp\n"
                             << "Program will terminate\n";
                   exit(EXIT_FAILURE);
               }
               int tmp = lasfile.tellg();
               lasfile.seekg(wave_offset);
               lasfile.read((char *) wave_data,point_info.wf_packet_size_in_bytes);
               i_pulseManager->addPoint(point_info,wave_data,wave_offset);
               lasfile.seekg(tmp);
               delete []wave_data;
         }
         else if (point_info.wave_packet_descriptor_index!=0)
         {
             i_pulseManager->addPoint(point_info,wave_offset);
             countDiscrete++;
             // no waveform associated with the data
         }
          else
          {
              discreteWithoutWaveform++;
          }
       }
       else
       {
           // only noise has been recorded
       }
    }
    if(count==0)
    {
        std::cout << "no waveforms associated with that area\n";
    }
    else
    {
        std::cout << count << " waveforms found\n";
        std::cout << count+countDiscrete << " discrete points found\n";
    }
    //---------------------------------------------------------------
    i_pulseManager->sortDiscretePoints();
    std::cout << "There are " << discreteWithoutWaveform << " discrete points associated with no waveform and they have been discarded.\n";
    std::cout << "----------------------------------------------------\n";
    lasfile.close();
    return i_pulseManager;
 }
Member Data Documentation
const unsigned int Las1_3_handler::EVLR_length = 60 static private
Extended Variable Lenght Record Header, in Version 1.3 the only EVLR is waveform data packets.
Definition at line 84 of file Las1_3_handler.h.
int* Las1_3_handler::i_hist protected
the intensity histogram of the lasfile
Definition at line 48 of file Las1_3_handler.h.
std::ifstream Las1_3_handler::lasfile private
saved here to avoid opening and closing the file multiple times
Definition at line 71 of file Las1_3_handler.h.
std::string Las1_3_handler::m_filename protected
the name of the LAS file
Definition at line 40 of file Las1_3_handler.h.
Types::Leica_mission_info Las1_3_handler::mis_info protected
Leica mission information.
Definition at line 52 of file Las1_3_handler.h.
const unsigned int Las1_3_handler::point_data_length = 57 static private
the length of the point data
Definition at line 88 of file Las1_3_handler.h.
Types::Public_Header_Block Las1_3_handler::public_header protected
the publi header block of the LAS1.3 file
Definition at line 44 of file Las1_3_handler.h.
const unsigned int Las1_3_handler::public_header_length = 235 static private
Public Header length in bytes.
Definition at line 75 of file Las1_3_handler.h.
const unsigned int Las1_3_handler::VbleRec_header_length = 54 static private
Variable Length Record Header length in bytes.
Definition at line 79 of file Las1_3_handler.h.
Types::WF_packet_Descriptor Las1_3_handler::wv_info protected
waveform packet descriptor
Definition at line 56 of file Las1_3_handler.h.
The documentation for this class was generated from the following files:
Las1_3_handler.h
Las1_3_handler.cpp